# vs 2017 image because Windows SDK 10.0.15063.0 is not available on vs 2015 image
image: Visual Studio 2017

platform:
- x64

install:
  - ps: |
        npm --loglevel=error i -g node-gyp 2>&1 | out-null
        if ($LASTEXITCODE -NE 0) { throw "Failed installing node-gyp"; }
  - ps: node -v
  - ps: npm -v
  - ps: node-gyp -v
  - cmd: npm --loglevel=error i
  - cmd: npm run build:source
  - cmd: npm run ci
  - ps: $publish_binary = 0
  - ps: if ($env:appveyor_repo_tag -match "true") { $publish_binary=1; }
  - ps: echo "tag $env:appveyor_repo_tag_name branch $env:APPVEYOR_REPO_BRANCH"
build_script:
  - ps: echo "publish $publish_binary"
  - ps: $arch = $env:platform
  - ps: if ($arch -match "x86") { $arch="ia32"; }
  - ps: |
      if ($publish_binary -Eq "1") {
        npm --loglevel=error i -g prebuild 2>&1 | write-host
        prebuild --all --upload $env:prebuild_upload 2>&1 | write-host
      }
      echo "done."
