# vs 2017 image because Windows SDK 10.0.15063.0 is not available on vs 2015 image
image: Visual Studio 2017

platform:
- x64

install:
  - ps: node -v
  - ps: npm -v
  - ps: yarn -v
  - ps: yarn global add node-gyp --loglevel=error
  - ps: node-gyp -v
  - cmd: yarn install --frozen-lockfile
  - cmd: yarn build:source
  - cmd: yarn ci
  - ps: $publish_binary = 0
  - ps: if ($env:appveyor_repo_tag -match "true") { $publish_binary=1; }
  - ps: echo "tag $env:appveyor_repo_tag_name branch $env:APPVEYOR_REPO_BRANCH"
build_script:
  - ps: echo "publish $publish_binary"
  - ps: $arch = $env:platform
  - ps: if ($arch -match "x86") { $arch="ia32"; }
  - ps: |
      if ($publish_binary -Eq "1") {
        yarn global add prebuild 2>&1 | write-host
        prebuild -t 12.16.0 -r node --upload $env:prebuild_upload 2>&1 | write-host
        prebuild -t 5.0.10 -r electron --upload $env:prebuild_upload 2>&1 | write-host
      }
      echo "done."
